# Generated by Django 4.1.1 on 2022-09-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_rename_sections_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='section',
            new_name='title',
        ),
    ]
