# Generated by Django 4.1.1 on 2022-09-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_title_description2_title_description3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='title',
            new_name='titles',
        ),
    ]
