# Generated by Django 4.1.2 on 2023-01-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_rename_title_title_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('paragraph', models.TextField(null=True)),
                ('paragraph2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='title',
        ),
    ]
