# Generated by Django 4.1.2 on 2023-01-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_news_delete_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
