# Generated by Django 4.1.2 on 2023-01-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='shortitle',
            field=models.TextField(null=True),
        ),
    ]
