# Generated by Django 4.1.1 on 2022-09-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sections',
            new_name='section',
        ),
    ]
